### ISSUE TITLE
Read and write JSON

### ISSUE THREAD

**Issue by Natendrtfm** [ArkScript-lang/modules#14]
**Is your feature request related to a problem? Please describe.**
Not really but if we wanna try to do information exchange with other programs, reading JSON could be nice

**Describe the solution you'd like**
Possibility of reading JSON

**Describe alternatives you've considered**
Something like a parseJSON(data) where data is the output of a readFile and the JSON is an object

**Comment by SuperFola** [comment]
ArkScript implementation details
```clojure
(json:toString json_object)
(json:fromString string)
(json:fromList [
    "key" "value"
    "test" 12
    "nested" (json:fromList ["a" "b"])
])
```
