### ISSUE TITLE
Add a (Python, bash?) script to generate the basic folder structure for a module

### ISSUE THREAD

**Issue by SuperFola** [ArkScript-lang/modules#36]
Should also generate a basic CMakeLists.txt

Blocked by #33

**Comment by Shylajhaa** [comment]
Is this issue open to work on?

**Comment by SuperFola** [comment]
Yes, it is!

If you want to work and this and have any question, feel free to ask

**Comment by fabien-zoccola** [comment]
However, be aware that the RFC regarding this directory structure has not been drafted yet; you might have to change things if the accepted RFC differs from the hierarchy proposed in issue #33.

**Comment by Shylajhaa** [comment]
> Yes, it is!
> 
> If you want to work and this and have any question, feel free to ask

Can you give me more context on the purpose of the script?

**Comment by fabien-zoccola** [comment]
Sure! First of all, the RFC regarding the directory structure, RFC-006, has been published yesterday, and thus the structure should not change anymore. You can find said RFC [here](https://github.com/ArkScript-lang/rfc/blob/master/006-modules-architecture.md). 

> Can you give me more context on the purpose of the script?

The script would be used to generate the directory structure referenced above, to be used when contributors or members of the dev team want to start writing a new module. Said script would generate all files and folders following the structure declared in RFC-006.

I hope this helps! If you still have any questions, feel free to ask

**Comment by Shylajhaa** [comment]
Yeah, this works. I'll raise a Pull request once done.

**Comment by SuperFola** [comment]
I'm assigning this to you then!

**Comment by Shylajhaa** [comment]
Can you give me access to write to this repo? Trying to push a new branch
